### ISSUE TITLE
A blank shorting is shown

### ISSUE THREAD

**Issue by hossainalikram** [mozmeao/lumbergh#202]
![untitled](https://user-images.githubusercontent.com/8605491/29026070-bbf7b7d0-7b9b-11e7-96fd-b62544f55b71.png)

Direct me to files or if you can mentor, I can fix this

**Comment by glogiotatidis** [comment]
Thanks for reporting @hossainalikram. 

The real source of this problem is incomplete data from the job listing board. At the point you checked there was at least one job position with no defined `position type`. I guess we can filter out that empty line from the dropdown as a workaround to incomplete data.

Feel free to send a pull request to fix this and I'll review.

**Comment by anbenson** [comment]
I can't reproduce this bug anymore - maybe it's fixed and we should close? But I also don't see "Student Worker" or "Temporary" as options anymore.

**Comment by glogiotatidis** [comment]
> I can't reproduce this bug anymore - maybe it's fixed and we should close? But I also don't see "Student Worker" or "Temporary" as options anymore.

Those lists get auto-populated from the data we receive from the position management platform. You can't replicate b/c the positions with false data have been either fixed or closed. 

The issue is still valid is one want to submit a PR to prevent empty options to appear

**Comment by glogiotatidis** [comment]
With the new site redesign this is not longer valid. Thanks for reporting! :cake:
