### ISSUE TITLE
Greenhouse Sync Crashing

### ISSUE THREAD

**Issue by pmac** [mozmeao/lumbergh#211]
I've paused the DMS alerts for now. I see a lot of the following in the logs:

```
Clock job job_syncgreenhouse@careers-prod: CRASHED: get() returned more than one Position -- it returned 2!
```

I'm guessing that means something in the data, probably on the greenhouse side, is wrong. Doesn't seem like an emergency however as it's only been since around 22:00UTC, so I'm just filing this to be dealt with tomorrow.

@glogiotatidis

**Comment by glogiotatidis** [comment]
Thanks for pausing snitch and reporting @pmac.

This happens once every quarter or so. What I do to fix is manually delete the job with the conflicting ID.

It could be Greenhouse returning a JSON with the same job twice, or somehow our Deis v1 not running the job properly. Since this is a rare event it's hard to debug.

I pushed https://github.com/mozmeao/lumbergh/pull/212 to prod to help us collect some info if and when that happens again.

**Comment by glogiotatidis** [comment]
ftr this was caused by a second cron job running on the upcoming portland cluster. the two jobs where updating the db at the same time
