### ISSUE TITLE
Videos on careers homepage are 404

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/lumbergh#354]
STR:

1. Visit https://careers.mozilla.org/
2. Scroll down to "Community & Culture"
3. Click on either of the video thumbnails.

Expected results:

Modal should open and video should play.

Actual results:

Videos are 404:

```
HTTP load failed with status 404. Load of media resource https://assets.mozilla.net/video/careers/Firefox_Monument_2014.mp4 failed.
```

```
HTTP load failed with status 404. Load of media resource https://assets.mozilla.net/video/careers/rubic-cube.mp4 failed.
```

**Comment by jgmize** [comment]
@craigcook it looks like you added these videos in https://github.com/mozmeao/lumbergh/commit/4c07aa8a4a880828765cff19f838b47f1b45c8fb but perhaps forgot to upload them to the assets s3 bucket?

**Comment by craigcook** [comment]
Looks like [I broke this right here](https://github.com/mozmeao/lumbergh/blob/master/careers/careers/static/js/careers.js#L585-L586). 

But I also think we need to move those videos off the old video CDN anyway so I'll upload them to S3 as the easier fix (rather than change the JS to support different URL paths). Once the files are in place this should just fix itself without any code changes in lumbergh.

**Comment by craigcook** [comment]
Home page videos have been uploaded to S3 in mp4 and webm formats, and they're working for me. If someone has a moment to verify we can close this issue (I don't have closing powers in this repo).

**Comment by metadave** [comment]
works for me
