### ISSUE TITLE
set up DMS monitoring for pulling blog posts during build

### ISSUE THREAD

**Issue by jpetto** [mozmeao/lumbergh#434]
failing to pull in blog posts shouldn't result in a failed build/release of the site, but we should be monitoring the success/failure of pulling this external data.

**Comment by glogiotatidis** [comment]
1. Create a new Snitch on DMS, use a descriptive name. Set interval to one day since we trigger automatic site rebuilds at least once per day.  
2. Create an entry in `settings.py` to set the Snitch URL via env variables. See for example https://github.com/mozmeao/snippets-service/blob/master/snippets/settings.py#L270
3. Set the env variable in GitLab https://gitlab.com/mozmeao/lumbergh/-/settings/ci_cd
4. Ping the DMS URL (when set) with a `requests.get` right after fetching blog posts completes and within the try/except block. This will ensure the the DMS URL only gets pinged when blog post fetching and parsing complete without issues.
5. Profit!
