### ISSUE TITLE
Search in URL is reset on page load in some circumstances

### ISSUE THREAD

**Issue by pmac** [mozmeao/lumbergh#607]
I noticed this when I was looking at the internship page and clicked the `Apply for an internship` button and it took me to the full list of offerings. I tried it again and noticed that it was actually doing an immediate redirect from `/listings/?position_type=Intern` to just `/listings/`. This makes it seem like the full list is for intern positions. I can also reproduce this if I go to the listings page and add some filters and then refresh the page. The filtering resets. 

My theory is that the JS is behaving oddly because there is currently a listing that does not include any data in the `Position` field. This is causing a blank entry to show up in the filter drop down and perhaps is causing a JS error that is causing the filtering issues.

**Comment by helfi92** [comment]
It looks like the internships menu item was set to an empty string.

<img width="513" alt="Screen Shot 2020-11-03 at 12 40 50 PM" src="https://user-images.githubusercontent.com/3766511/98021097-e0b10500-1dd1-11eb-96df-7e8d926f9cbb.png">

Navigating to `/listings/?position_type=Intern` ends up redirecting to `/listings/` since the intern dropdown menu item does not exist.

Possible actions to take:
* Remove the internships top menu from the careers site. My understanding is that we won't have interns for a while now.
* Delete the empty string from wherever it's coming from (greenhouse?)

I don't currently have access to greenhouse so perhaps someone else can remove that empty string. @pmac any idea who has access?

**Comment by ccooper** [comment]
Looking at the list of open positions, I see a "Lab Lead" role that is missing a position (or has an empty position) and may be responsible for this:

<img width="1070" alt="Screen Shot 2020-11-03 at 10 31 55 PM" src="https://user-images.githubusercontent.com/609786/98066277-93aa4e80-1e24-11eb-9b3e-32fff5260aca.png">

I'd recommend guarding against the empty string when we're building the drop down list here: https://github.com/mozmeao/lumbergh/blob/master/careers/careers/forms.py#L24

**Comment by glogiotatidis** [comment]
From a developer standpoint I agree with you. I brought a similar suggestion to HR back in the day and they insisted on not enforcing this on our backend and instead they would provide clear instructions to hiring managers. 

Since then this error appears a lot less but it still happens from time to time. I lean towards not enforcing myself, because we don't have a feedback process to let hiring managers know why their position is not listed although it's published on greenhouse. 

If only we could enforce filling this field on GH.


edit: I re-read your comment and I saw that you suggest altering only the drop down to not include the empty item. Go for it!

**Comment by helfi92** [comment]
Closing as resolved.
